services:
  # Go Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: orlando-backend
    restart: unless-stopped
    environment:
      # Server Configuration
      PORT: 8080
      ENVIRONMENT: production
      
      # Database Configuration
      DATABASE_URL: /app/data/orlando.db
      DATABASE_TYPE: sqlite
      
      # Security Configuration
      JWT_SECRET: ${JWT_SECRET:-CHANGE-THIS-TO-A-STRONG-RANDOM-SECRET-AT-LEAST-32-CHARACTERS-LONG}
      JWT_EXPIRATION_HOURS: 24
      
      # CORS Configuration
      ALLOWED_ORIGINS: https://frankcation.com,https://www.frankcation.com
      
      # File Upload Configuration
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: 52428800
      ALLOWED_FILE_TYPES: image/jpeg,image/png,image/jpg,video/mp4,video/quicktime,video/mov
      
      # Rate Limiting
      RATE_LIMIT: 50
      RATE_LIMIT_BURST: 100
      
      # Logging
      LOG_LEVEL: info
    volumes:
      - uploads_data:/app/uploads
      - sqlite_data:/app/data
    ports:
      - "8080:8080"
    networks:
      - orlando-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/leaderboard"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend with Simple HTTP Server
  # NOTE: This serves only static files on port 3000
  # API proxying (/api/, /auth/, /uploads/) should be handled by external reverse proxy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - EXPO_PUBLIC_API_BASE_URL=https://frankcation.com
        - EXPO_PUBLIC_ENVIRONMENT=production
        - EXPO_PUBLIC_ENABLE_DEBUG=false
        - EXPO_PUBLIC_ENABLE_ANALYTICS=true
    container_name: orlando-frontend
    restart: unless-stopped
    ports:
      - "3003:3000"
    networks:
      - orlando-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Named volumes for data persistence
volumes:
  sqlite_data:
    driver: local
  uploads_data:
    driver: local

# Custom network
networks:
  orlando-network:
    driver: bridge

# Add labels for better organization
x-common-labels: &common-labels
  com.frankcation.project: "orlando-challenge"
  com.frankcation.environment: "production"